name: fastem
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - jupyterlab
  - ipython
  - altair
  - vega_datasets
  - nodejs=15
  - mamba
  - pip
  - numpy
  - git
  - tifffile
  - pip:
    - tqdm
    - lxml
    - ipympl
    - ipywidgets
    - imagecodecs
    - ruamel.yaml
    - bigfeta